#pragma once

enum loggerFlags
{
    PNT_LOGGER_FLAGS_NOTE,
    PNT_LOGGER_FLAGS_WARNING,
    PNT_LOGGER_FLAGS_ERROR,
    PNT_LOGGER_FLAGS_FATAL
};

enum vsyncFlags
{
    PNT_VSYNC_FLAGS_OFF,
    PNT_VSYNC_FLAGS_ON,
    PNT_VSYNC_FLAGS_ADAPTIVE,
};

enum callbackFlags
{
    PNT_CALLBACK_FLAGS_EVENT,
    PNT_CALLBACK_FLAGS_STARTFRAME,
    PNT_CALLBACK_FLAGS_ENDFRAME
};
