#pragma once

enum loggerFlags : uint8_t {
    PNT_LOGGER_FLAGS_NOTE,
    PNT_LOGGER_FLAGS_WARNING,
    PNT_LOGGER_FLAGS_ERROR,
    PNT_LOGGER_FLAGS_FATAL
};

enum vsyncFlags : int8_t {
    PNT_VSYNC_FLAGS_ADAPTIVE = -1,
    PNT_VSYNC_FLAGS_OFF,
    PNT_VSYNC_FLAGS_ON,
};

enum callbackFlags : uint8_t {
    PNT_CALLBACK_FLAGS_STARTFRAME,
    PNT_CALLBACK_FLAGS_ENDFRAME,
    PNT_CALLBACK_FLAGS_COUNT,
};

enum eventCallbackFlags : uint8_t {
    PNT_EVENT_TYPE_KEYBOARD,
    PNT_EVENT_TYPE_CHAR,
    PNT_EVENT_TYPE_DROP,
    PNT_EVENT_TYPE_SCROLL,
    PNT_EVENT_TYPE_CURSORPOS,
    PNT_EVENT_TYPE_WINDOWPOS,
    PNT_EVENT_TYPE_WINDOWSIZE,
    PNT_EVENT_TYPE_MOUSEBUTTON,
    PNT_EVENT_TYPE_ICONIFY
};
